# Generated by Django 2.0.5 on 2019-07-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190726_1651'),
        ('shop', '0007_auto_20190723_1638'),
    ]

    operations = [
    ]
