# Generated by Django 2.1.5 on 2019-07-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cell_phone',
            field=models.CharField(default='9999999999', max_length=50),
        ),
    ]
